version: "2"
services:
  reverseproxy:
    build: ./nginx
    ports:
        - 80:80
    restart: always
  api:
    depends_on:
        - reverseproxy
    build: ./api
    command: npm run start:prod
    links:
      - mongo
  web:
    depends_on:
        - reverseproxy
    build: ./web
    command: npm run start:prod
    links:
      - mongo
  mongo:
    image: mongo