version: "2"
services:
  api:
    command: npm run start:dev
    volumes:
      - app_volume_sync:/app:nocopy
  web:
    command: npm run start:dev
    volumes:
      - web_volume_sync:/app:nocopy

volumes:
  app_volume_sync:
    external: true
  web_volume_sync:
    external: true