version: "2"
services:
  api:
    build: ./api
    command: npm run start:prod
    ports:
      - "4000:3000"
    links:
      - mongo
  web:
    build: ./web
    command: npm run start:prod
    ports:
      - "2000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "23013:27017"